name: 'Test: Build and prewiew Vitepress'

on:
  pull_request:
    branches: [main]

permissions:
  statuses: write
  checks: write
  pull-requests: write

jobs:
  prewiew-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Change vitepress base config
        run: |
          sudo apt-get install jq
          echo $(jq '.base = "/pr-preview/pr-${{ github.event.number }}}/"' ./.vitepress/config.json) > ./.vitepress/config.json 
      - name: Parsing info about members from git
        run: |
          npm run history:build -- --key="${{ secrets.GITHUB_TOKEN }}" --debug
      - name: Build with VitePress
        run: |
          npm run docs:build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .vitepress/dist